Alteração para botões e outras funções em css
tdqc/ProjetoEstudo pull request #2
Opened 2018-12-16 21:30 UTC by tdqc

O negrito, ao invés de usar <b>, usei css e no botão tirei o <a> e coloquei <button> diretamente

2018-12-17 05:54 UTC, tdqc commented
as outras funções são o negrito dos parágrafos e legends

2018-12-18 21:30 UTC, IannMuller requested changes

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-alterar-cliente.html
> +            legend.negrito{font-weight: bold;}
fica mais legivel quando tem um espaço separando as chaves, tanto antes quando depois.
ex.: legend.negrito { font-weight: bold; }

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-alterar-cliente.html
> +            legend.negrito{font-weight: bold;}
Como tanto p.negrito quanto legend.negrito usam exatamente o mesmo CSS tu pode criar um .bold { font-weight: bold; }, isso evita duplicaçao de codigo

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-consultar-cliente.html
> +                <pre>
qual o proposito de uma tag de texto vazia?

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/menu-cliente.html
> +                            Clique aqui para <strong> deletar </strong> um cliente
nos a de cima tu botou a tag strong sem espaço, por questao de padrao de projeto tu tem que escolher sempre ter esse espaço ou nao ter em todos

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/menu-principal.html
>  </html>
falta a linha em vazia no final do documento

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/index.html
>  </html>
falta a linha em vazia no final do documento

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-inserir-cliente.html
>  </html>
falta a linha em vazia no final do documento

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-deletar-cliente.html
>  </html>
falta a linha em vazia no final do documento

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-consultar-cliente.html
>  </html>
falta a linha em vazia no final do documento

2018-12-18 21:30 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/formulario-alterar-cliente.html
>  </html>
falta a linha em vazia no final do documento

2018-12-21 02:31 UTC, IannMuller requested changes

2018-12-21 02:31 UTC, IannMuller commented on front-loja1/public_html/_principal/_cliente/menu-cliente.html
> +                            Clique aqui para <strong> deletar </strong> um cliente
mesmo esquema que no outro branch

2018-12-22 00:44 UTC, IannMuller approved these changes

2018-12-22 01:32 UTC, merged